"""Refresh the interactive Win chart on docs/dashboard/vio.html from the multilap artifacts:

- the JS data block (between the WIN3LAP_DATA markers) from data/vio_tracks_3lap.json
- the chart script block (between the WIN3LAP_JS markers) — shared renderer in trackchart.py
  plus this page's series/readout config below
- the no-JS/print fallback image (img id="winfallback") from renders/stage2_vio_3lap.png
- the drift-vs-time card image (img id="windrift") from renders/stage2_vio_3lap_drift.png

Run after `run_vio.py multilap`:  python3 scripts/embed_vio_win.py
"""
import json
import os

from trackchart import TRACKCHART_JS, splice, swap_img

HERE = os.path.dirname(__file__)
ROOT = os.path.abspath(os.path.join(HERE, ".."))
PAGE = os.path.join(ROOT, "docs", "dashboard", "vio.html")
TRACKS = os.path.join(ROOT, "data", "vio_tracks_3lap.json")

# Page config for the shared renderer: one GT track + three estimator tracks, all on the shared
# 10 Hz time grid, hover shows the live gap / |yaw err| of every visible estimator.
WIN_CFG = """
(function(){
  var D=window.WIN3;if(!D)return;
  var names=["leg-odom","ESKF","VIO"],
      col={"gt":"#d7e2ee","leg-odom":"#e0a030","ESKF":"#e05050","VIO":"#3fd0c9"};
  var series=[{pts:D.gt,color:col.gt,dash:[6,5],lw:1.6,groups:["gt"],scan:true}];
  names.forEach(function(n){series.push({pts:D.est[n].xy,color:col[n],groups:[n],scan:true,mark:true});});
  TrackChart({
    wrap:"winwrap",canvas:"winchart",legend:"winlegend",readout:"winread",fallback:"winfallback",
    series:series,
    groups:[{key:"gt",label:"ground truth",color:col.gt},
            {key:"leg-odom",label:"leg-odom",color:col["leg-odom"]},
            {key:"ESKF",label:"ESKF",color:col.ESKF},
            {key:"VIO",label:"VIO",color:col.VIO}],
    start:{p:D.gt[0],label:"start — every lap ends here ("+D.laps+"×)"},
    idle:"hover the tracks — "+D.laps+" laps · "+(D.laps*D.period_s).toFixed(0)+
      " s · "+D.path_m+" m path · uncalibrated gyro-z bias "+D.imu_bias_z_dps+
      " °/s · final gap: leg-odom "+D.final_pos_err_cm["leg-odom"]+" · ESKF "+
      D.final_pos_err_cm["ESKF"]+" · VIO "+D.final_pos_err_cm["VIO"]+" cm",
    fmt:function(si,i,on){
      var t=D.t[i],lap=Math.min(D.laps,Math.floor(t/D.period_s)+1),
          h="t "+t.toFixed(1)+" s · lap "+lap+" · GT x "+D.gt[i][0].toFixed(2)+
            ", y "+D.gt[i][1].toFixed(2)+" m";
      names.forEach(function(n){
        if(!on[n])return;
        h+=" · <span style=\\"color:"+col[n]+"\\">"+n+" "+(D.est[n].err_m[i]*100).toFixed(0)+
           " cm / "+D.est[n].yaw_err_deg[i].toFixed(1)+"°</span>";
      });
      return h+" <span style=\\"color:var(--faint)\\">(gap / |yaw err|)</span>";
    }
  });
})();
"""


def main():
    html = open(PAGE).read()
    with open(TRACKS) as f:
        data = f.read()
    json.loads(data)                                   # validate before splicing
    html = splice(html, "WIN3LAP_DATA",
                  "<!-- WIN3LAP_DATA_START (regenerated by scripts/embed_vio_win.py from "
                  "data/vio_tracks_3lap.json) -->\n<script>window.WIN3=" + data
                  + ";</script>\n<!-- WIN3LAP_DATA_END -->")
    html = splice(html, "WIN3LAP_JS",
                  "<!-- WIN3LAP_JS_START (regenerated by scripts/embed_vio_win.py — shared "
                  "renderer: scripts/trackchart.py) -->\n<script>"
                  + TRACKCHART_JS + WIN_CFG + "</script>\n<!-- WIN3LAP_JS_END -->")
    html = swap_img(html, "winfallback", os.path.join(ROOT, "renders", "stage2_vio_3lap.png"))
    html = swap_img(html, "windrift", os.path.join(ROOT, "renders", "stage2_vio_3lap_drift.png"))
    open(PAGE, "w").write(html)
    print(f"updated {PAGE} ({os.path.getsize(PAGE) // 1024} KB)")


if __name__ == "__main__":
    main()
